spring:
  application:
    name: demo-springboot
  banner:
    image:
      location: banner.txt

server:
  port: 9090
  servlet:
    context-path: /demo/

hello:
  name:
    lisi

logging:
  file: d:/logs/demo-springboot
  level:
    com:
      demo:
        springboot:
          debug

